name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-versions: '8.0'
            laravel-versions: '^9.0'
          - php-versions: '8.1'
            laravel-versions: '^9.0'
          - php-versions: '8.1'
            laravel-versions: '^10.0'
          - php-versions: '8.2'
            laravel-versions: '^10.0'
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}

    - name: Setup Laravel
      run: composer require -W --dev laravel/laravel:${{ matrix.laravel-versions }}

    - name: Run tests
      run: ./vendor/bin/phpunit

